version: '3.1'

services:

  db:
    image: mariadb
    healthcheck:
      test: [ "CMD", "/usr/local/bin/healthcheck.sh" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: mariadb


  django:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "80:8000"
    depends_on:
      db:
        condition: service_healthy

  adminer:
    image: adminer
    restart: always
    ports:
      - "5000:5000"
